# Generated by Django 3.2.3 on 2021-05-28 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=20, unique=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='TemperaturaHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('temperatura', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Temperatura')),
                ('humedad', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Humedad')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.ciudad', verbose_name='Ciudad proveniente')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.pais', verbose_name='País'),
        ),
    ]
