# Generated by Django 3.2.3 on 2021-05-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturahumedad',
            options={'verbose_name': 'Temperatura y humedad', 'verbose_name_plural': 'Temperaturas y humedades'},
        ),
    ]
